spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssmbuild?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl